// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ddFSUXsVUh0Pix5KYgRF0bDidxkQ1kw',
    appId: '1:858956405989:web:ea007c4c482a1c1d27480c',
    messagingSenderId: '858956405989',
    projectId: 'eventospf-8622d',
    authDomain: 'eventospf-8622d.firebaseapp.com',
    storageBucket: 'eventospf-8622d.firebasestorage.app',
    measurementId: 'G-VWTNPECFXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWBNh16Dv8ACpzwW-6I05Ch0sp5VBHa9o',
    appId: '1:858956405989:android:31ed7b63c8ada69827480c',
    messagingSenderId: '858956405989',
    projectId: 'eventospf-8622d',
    storageBucket: 'eventospf-8622d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzHF02dCvbAXFo4thqm4Tyo1_q_CQ-cj8',
    appId: '1:858956405989:ios:68a103ae072205cc27480c',
    messagingSenderId: '858956405989',
    projectId: 'eventospf-8622d',
    storageBucket: 'eventospf-8622d.firebasestorage.app',
    iosBundleId: 'com.grupopf.pfevents',
  );
}
